version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: globalonline-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: formacionglobal
    volumes:
      - mongo_data:/data/db
      - ./MongoDB:/seed:ro
      - ./MongoDB/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

volumes:
  mongo_data:
